// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Market.Models
{
    public partial class Order
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string PersonName { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal TotalPrice { get; set; }
        public int StockId { get; set; }

        [ForeignKey("StockId")]
        [InverseProperty("Orders")]
        public virtual Stock Stock { get; set; }
    }
}