// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Market.Models
{
    public partial class Stock
    {
        public Stock()
        {
            Orders = new HashSet<Order>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal Price { get; set; }

        [InverseProperty("Stock")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}